name: Publish to Node

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        id: checkout_code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Node
        id: setup_node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org/'

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install core dependencies
        run: |
          cd packages/core
          pnpm install

      - name: Build core
        run: |
          cd packages/core
          pnpm build

      - name: Publish core to npm
        run: |
          cd packages/core

          VERSION=$(node -p "require('./package.json').version")
          PKG=$(node -p "require('./package.json').name")
      
          if npm view $PKG@$VERSION > /dev/null 2>&1; then
            echo "Version $VERSION already exists. Skipping publish."
            exit 0
          fi

          npm publish --provenance --access public
        env:
          NPM_CONFIG_PROVENANCE: true

      - name: Install mobile and extension dependencies
        run: pnpm i --frozen-lockfile

      - name: Build mobile and extension
        run: pnpm build

      - name: Publish mobile to npm
        run: |
          cd packages/mobile

          VERSION=$(node -p "require('./package.json').version")
          PKG=$(node -p "require('./package.json').name")
      
          if npm view $PKG@$VERSION > /dev/null 2>&1; then
            echo "Version $VERSION already exists. Skipping publish."
            exit 0
          fi

          npm publish --provenance --access public
        env:
          NPM_CONFIG_PROVENANCE: true

      - name: Publish extension to npm
        run: |
          cd packages/extension

          VERSION=$(node -p "require('./package.json').version")
          PKG=$(node -p "require('./package.json').name")
      
          if npm view $PKG@$VERSION > /dev/null 2>&1; then
            echo "Version $VERSION already exists. Skipping publish."
            exit 0
          fi

          npm publish --provenance --access public
        env:
          NPM_CONFIG_PROVENANCE: true
